Implemented Date/Time/DateTime Picker
afollestad/material-dialogs pull request #1748
Opened 2019-03-18 11:12 UTC by guger

2019-03-18 17:35 UTC, afollestad requested changes

2019-03-18 17:35 UTC, afollestad commented on datetime/proguard-rules.pro
> +# Add project specific ProGuard rules here.
This file can be deleted

2019-03-18 17:35 UTC, afollestad commented on datetime/src/main/AndroidManifest.xml
> +<manifest xmlns:android="http://schemas.android.com/apk/res/android"
Since this is a library module, this whole can be: 
```xml
<manifest package="com.afollestad.materialdialogs.datetime" />
```

2019-03-18 17:35 UTC, afollestad commented on datetime/src/main/java/com/afollestad/materialdialogs/datetime/DateTimePickerAdapter.kt
> +    when (position) {
This should be simplified to:
```kotlin
val resId = when(position) {
    0 -> R.id.datetimeDatePicker
    1 -> R.id.datetimeTimePicker
    else -> throw IllegalStateException("Unexpected position: $position")
}
return container.findViewById(resId)
```

2019-03-18 17:35 UTC, afollestad commented on datetime/src/main/java/com/afollestad/materialdialogs/datetime/DialogDateTimePickerExt.kt
> +  positiveButton(res = android.R.string.ok) {
`res = ` isn't unnecessary here or below

2019-03-18 17:35 UTC, afollestad commented on datetime/src/main/java/com/afollestad/materialdialogs/datetime/utils/ViewExt.kt
> +fun isNougat() = Build.VERSION.SDK_INT >= Build.VERSION_CODES.N
This should probably be `private`

2019-03-18 17:35 UTC, afollestad commented on datetime/src/main/java/com/afollestad/materialdialogs/datetime/utils/ViewExt.kt
> +@Suppress("DEPRECATION")
Rather than having this suppression on each method, it can be at the top of the file (IntelliJ has an option for that when you do Alt+Enter)

2019-03-18 17:35 UTC, afollestad commented on dependencies.gradle
>  ext.versions = [
The re-formatting to this file should be undone

2019-03-18 17:35 UTC, afollestad commented on sample/src/main/java/com/afollestad/materialdialogssample/MainActivity.kt
> +import kotlinx.android.synthetic.main.activity_main.*
This should be undone

2019-03-18 17:35 UTC, afollestad commented on sample/src/main/java/com/afollestad/materialdialogssample/MainActivity.kt
> +          R.array.socialNetworks, initialSelection = 1, disabledIndices = intArrayOf(1, 3)
All of this other formatting should be undone as well

2019-03-18 17:35 UTC, afollestad commented on sample/src/main/res/layout/activity_main.xml
> +        xmlns:android="http://schemas.android.com/apk/res/android"
This formatting should be undone

2019-03-18 19:44 UTC, afollestad approved these changes
Looks good, thank you! Will merge once the build passes

2019-03-18 19:59 UTC, merged

2021-12-06 05:49 UTC, YTopTool commented
![1599361638769075_ pic](https://user-images.githubusercontent.com/78673952/144794205-8d8d41c6-f746-40a3-9dc4-4310155e64c4.jpg)